[package]
name = "ping-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping-rs = "0.1"
chrono = "0.4"
ctrlc = "3"
config = "0"